apiVersion: v1
kind: Secret # Para criptografar a senha do banco
metadata:
  name: mysql-secret
type: Opaque
stringData:
  password: wordpress-2020

---
# PVC - Volume: manter integra as informações dos pods, fazendo o mapeamento específico sem perder dados
# Para o banco MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Espaço para o armazenamento (1 giga)

---
# Para o Wordpress
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi