# Service - Gerenciar as camadas de rede dentro do kube. Como os deploy se comunicam entre eles. Como também comunicar com a internet via ip
# Como o banco se comunica com a aplicação wordpress
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP # O Padrão é ClusterIP
  selector: # Faz a ligação com o outro deploy (através da tag matchLabels)
    app: mysql-deployment
  ports:
  - port: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer # Responsável por fazer a comunicação com o mundo externo (Balanceamento de carga pelo kubernetes)
  selector:
    app: wordpress-deployment
  ports:
  - port: 80